
# Server Configuration
server:
    port: 8081
    
spring:
 data: 
  rest:
   defaultMediaType: application/json
  mongodb:
   uri: mongodb://wynatsorg:wynatsAtunes2@ds135107.mlab.com:35107/wynats
   database: wynats
  application:
     name: wynats-portfolio-api

# Discovery Server Access
eureka:
  client:
    registerWithEureka: true # El gateway no se registra, solo los microservicios
   # fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
 
