
# Server Configuration
server:
    port: 8081
    
spring:
 data: 
  rest:
   defaultMediaType: application/json
  mongodb:
   #uri: mongodb://wynats:atun3s@ds125574.mlab.com:25574/wynats

   uri: mongodb://mongo:w7n4tS.@27017/wynats

   database: portfolio