# Server Configuration
server:
  port: 8082
  
# Spring properties    
spring:
  application:
    name: wynats-portfolio-api
  data: 
    rest:
      defaultMediaType: application/json
  mongodb:
    uri: mongodb://mongodb/demorest #mongodb://wynatsorg:wynatsAtunes2@ds135107.mlab.com:35107/wynats?serverSelectionTimeoutMS=20000&connectTimeoutMS=20000
    database: wynats
    host: mongodb
    port: 27017
  datasource:
    driverClassName: MongoDB  

# Discovery Server Access
eureka:
  client:
    registerWithEureka: true 
    serviceUrl:
      defaultZone: {EUREKA_CLIENT_SERVICEURL_DEFAULTZONE} #http://localhost:8761/eureka
 