
# Server Configuration
server:
    port: 8081
    
spring:
 data: 
  rest:
   defaultMediaType: application/json
  mongodb:
   uri: mongodb://wynatsorg:wynatsAtunes2@ds135107.mlab.com:35107/wynats
   database: wynats

