
# Server Configuration
server:
    port: 8081
    
spring:
 data: 
  rest:
   defaultMediaType: application/json
  mongodb:
   uri: mongodb://wynats:w7n4tS.@mongo:27017/admin #   mongodb://<dbuser>:<dbpassword>@ds125574.mlab.com:25574/wynats
   database: admin

